### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: browserType.launch: Failed to launch webkit because executable doesn't exist at /app/node_modules/playwright-chromium/.local-browsers/webkit-1322/pw_run.sh

### ISSUE THREAD

**Issue by kicks66** [mxschmitt/heroku-playwright-example#5]
I've been trying to use this to deploy a Chromium based app, and I keep receiving the above error:

`UnhandledPromiseRejectionWarning: Error: browserType.launch: Failed to launch webkit because executable doesn't exist at /app/node_modules/playwright-chromium/.local-browsers/webkit-1322/pw_run.sh`

I am using the app.json from this file, and my dependencies look like so:

```
"dependencies": {
    "playwright-chromium": "^1.3.0"
  }
```

I'm not sure why its asking about webkit, considering its looking at chromium.

**Comment by mxschmitt** [comment]
Hi, which buildpacks are you using for your setup? Its important that the Heroku Playwright buildpack is placed as a first buildpack.

**Comment by mxschmitt** [comment]
btw. WebKit is not supported. Only Firefox and Chromium with the direct packages. (playwright-firefox and playwright-chromium)

**Comment by mxschmitt** [comment]
closed since you have to use `playwright-firefox` or `playwright-chromium` NPM packages.
